#!/bin/sh -ef 

_()
{
	LANG=${in_language%%;*}.utf8 gettext 'alterator-dhcp' "$1"
}


. /usr/share/alterator/build/backend3.sh

on_message()
{
	case "$in_action" in
		#information for renderer
		template)
			echo '('
			echo ' template "form" '
			echo ' help "dhcp.html"'
			echo ' translate "alterator-dhcp"'
			if [ "$in__objects" = "/" ];then
				echo ' url "dhcp-list.html"'
			else
				echo ' url "dhcp-subnet.html"'
				echo ' redirect "/dhcp"'
				#echo ' redirect #f'
			fi
			echo ')'
			;;
                info)
                        echo '('
                        printf ' title "%s"' "`_ "DHCP server"`"
                        printf ' description "%s"' "`_ "DHCP server administration"`"
                        printf ' group "%s"' "`_ "Network"`"
                        echo ')'
                        ;;
		*)
			echo '#f'
			;;
	esac
}


message_loop

