#!/bin/sh -ef 

. /usr/share/alterator/build/backend3.sh

on_message()
{
	case "$in_action" in
		#information for renderer
		template)
			echo '('
			echo ' template "form" '
			echo ' translate "alterator-dhcp"'
			if [ "$in__objects" = "/" ];then
				echo ' url "dhcp-list.html"'
			else
				echo ' url "dhcp-subnet.html"'
				echo ' redirect "/dhcp"'
				#echo ' redirect #f'
			fi
			echo ')'
			;;
		*)
			echo '#f'
			;;
	esac
}


message_loop

